#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
rm $(find constant/polyMesh ! -name "blockMeshDict")
rm -r constant/polyMesh/sets
rm -r VTK
rm log.*


# -----------------------------------------------------------------------------
