#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication snappyHexMesh -overwrite
cat constant/polyMesh/boundary | sed 's/Heavy.*/Heavy/' > constant/polyMesh/boundary2
cat constant/polyMesh/boundary2 | sed 's/Light.*/Light/' > constant/polyMesh/boundary3
rm constant/polyMesh/boundary
rm constant/polyMesh/boundary2
mv constant/polyMesh/boundary3 constant/polyMesh/boundary

cp 0/alpha1.org~ 0/alpha1
runApplication setFields
runApplication shipFoam
runApplication foamToVTK


# -----------------------------------------------------------------------------
